site_name: MLOps Project Documentation
site_description: Documentation for MLOps course homework implementations
repo_url: https://github.com/EgorovM/itmo-mlops-2025
repo_name: MLOps Project

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          paths: [src/mlops]
          options:
            show_source: true
            show_root_heading: true
            heading_level: 2
  - gen-files:
      scripts:
        - docs/gen_ref_pages.py
  - mkdocs-simple-hooks:
      hooks:
        on_post_build: "docs.hooks:copy_readme_hook"

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Project Structure: getting-started/project-structure.md
  - Data Version Control:
    - Overview: data-version-control/overview.md
    - Workflow: data-version-control/workflow.md
  - ML Pipeline:
    - Data Processing: ml-pipeline/data-processing.md
    - Model Training: ml-pipeline/model-training.md
    - Model Evaluation: ml-pipeline/model-evaluation.md
  - Development:
    - Contributing: development/contributing.md
    - Workflow: development/workflow.md
  - API Reference:
    - Core: api/core.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - tables 