name: CI Pipeline

on:
  push:
    branches:
      - main
      - release
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python

    - name: Install dependencies
      run: |
        . $HOME/.poetry/env && poetry install

    - name: Run linters
      run: |
        . $HOME/.poetry/env && flake8 .

    - name: Build Docker image
      run: |
        docker build . -t mlops-ods3.0:$GITHUB_SHA

    - name: Publish Docker image
      if: startsWith(github.ref, 'refs/heads/main') || startsWith(github.ref, 'refs/heads/release')
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: mlops-ods3.0
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and publish Python package
      if: startsWith(github.ref, 'refs/heads/main') || startsWith(github.ref, 'refs/heads/release')
      run: |
        . $HOME/.poetry/env && poetry build
        twine upload dist/*

    - name: Deploy to GitHub Pages
      if: startsWith(github.ref, 'refs/heads/main')
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
